import { StyleSheet, Dimensions } from 'react-native';
const { width, height } = Dimensions.get('window');
const isCompactHeight = height < 760;

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F4F6F8', position: 'relative' },

  // HEADER - Enhanced with gradient background
  headerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 18,
    paddingVertical: 16,
    backgroundColor: '#17263A',
    marginHorizontal: 16,
    marginTop: 8,
    marginBottom: 10,
    borderRadius: 24,
    position: 'relative',
  },
  headerGradient: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 0,
  },
  headerContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    zIndex: 1,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 10,
  },
  dashboardText: { fontSize: 28, fontWeight: '800', color: '#fff', letterSpacing: 0.5 },
  greetingText: { fontSize: 14, color: '#d0dfe8', marginTop: 4, fontWeight: '500' },

  // ✅ Profile Photo Styles
  headerProfileContainer: {
    width: 46,
    height: 46,
    borderRadius: 23,
    overflow: 'hidden',
    marginRight: 12,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.14)',
  },
  headerProfilePhoto: {
    width: 46,
    height: 46,
    borderRadius: 23,
  },
  headerProfilePlaceholder: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.12)',
  },

  // BELL - Enhanced notification icon
  bellContainer: {
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderRadius: 14,
    width: 40,
    height: 40,
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
  },
  supportContainer: {
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderRadius: 14,
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  badge: {
    position: 'absolute',
    top: -3,
    right: -3,
    backgroundColor: '#EF4444',
    width: 18,
    height: 18,
    borderRadius: 9,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#fff',
  },
  badgeText: { color: '#fff', fontSize: 9, fontWeight: '900' },
  supportModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  supportModalCard: {
    backgroundColor: '#fff',
    borderRadius: 14,
    paddingHorizontal: 18,
    paddingVertical: 16,
    width: '100%',
    maxWidth: 290,
    alignItems: 'center',
  },
  supportModalTitle: {
    marginTop: 8,
    fontSize: 16,
    fontWeight: '800',
    color: '#1a2f4d',
  },
  supportModalText: {
    marginTop: 6,
    fontSize: 13,
    color: '#4b5563',
    textAlign: 'center',
  },
  supportModalBtn: {
    marginTop: 12,
    backgroundColor: '#1a2f4d',
    borderRadius: 9,
    paddingHorizontal: 18,
    paddingVertical: 8,
  },
  supportModalBtnText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 13,
  },

  // TOP CARDS - Premium styling
  topRow: { 
    flexDirection: 'row', 
    justifyContent: 'space-between', 
    paddingHorizontal: 16,
    marginBottom: 12,
    marginTop: 4,
  },
  card: { 
    width: (width - 32 - 12) / 2,
    borderRadius: 22, 
    overflow: 'hidden',
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#E8EDF3',
    backgroundColor: '#fff',
  },
  fullWidthCard: { 
    width: width - 32, 
    borderRadius: 22, 
    overflow: 'hidden', 
    alignSelf: 'center', 
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#E8EDF3',
    backgroundColor: '#fff',
  },
  gradientCard: { 
    padding: 18, 
    alignItems: 'center', 
    justifyContent: 'center', 
    position: 'relative', 
    height: 126,
    borderRadius: 22,
  },
  bubble1: { 
    position: 'absolute', 
    width: 76, 
    height: 76, 
    backgroundColor: 'rgba(255,255,255,0.16)', 
    borderRadius: 38, 
    top: -18, 
    right: -18 
  },
  bubble2: { 
    position: 'absolute', 
    width: 50, 
    height: 50, 
    backgroundColor: 'rgba(255,255,255,0.12)', 
    borderRadius: 25, 
    bottom: -20, 
    left: -20 
  },
  amountTextWhite: { fontSize: 28, fontWeight: '700', color: '#fff', marginTop: 12, letterSpacing: 0.2, textAlign: 'center' },
  labelTextWhite: { fontSize: 13, color: 'rgba(255,255,255,0.8)', marginTop: 6, fontWeight: '600', letterSpacing: 0.2, textAlign: 'center' },
  // BANNER - Removed (discount banner)
  bannerContainer: { height: 0, display: 'none' },
  bannerImage: { height: 0, display: 'none' },

  // LEADERBOARD CONTAINER - Modern styling
  leaderboardWrapper: {
    minHeight: isCompactHeight ? 260 : 320,
    marginTop: 4,
    marginHorizontal: 16,
    marginBottom: 12,
    borderRadius: 24,
    padding: isCompactHeight ? 10 : 12,
    paddingBottom: 0,
    overflow: 'hidden',
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#E8EDF3',
  },
  leaderboardBackgroundGradient: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: 24,
    zIndex: 0,
  },
  leaderboardContent: {
    zIndex: 1,
  },
  leaderboardWrapperExpanded: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    height: '100%',
    marginTop: 0,
    borderRadius: 0,
    zIndex: 10,
    paddingTop: 50,
  },
  leaderboardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: isCompactHeight ? 2 : 4,
    paddingHorizontal: 4,
    paddingTop: 2,
  },
  expandButton: {
    padding: 6,
    borderRadius: 14,
    backgroundColor: '#F3F4F6',
  },
  leaderboardBubbles1: {
    position: 'absolute',
    width: 200,
    height: 200,
    backgroundColor: 'rgba(23, 38, 58, 0.05)',
    borderRadius: 100,
    top: -60,
    right: -60,
    zIndex: 0,
  },
  leaderboardBubbles2: {
    position: 'absolute',
    width: 120,
    height: 120,
    backgroundColor: 'rgba(102, 126, 234, 0.06)',
    borderRadius: 60,
    bottom: -40,
    left: -40,
    zIndex: 0,
  },
  leaderboardScroll: { 
    marginTop: 6, 
    paddingHorizontal: 4,
    paddingBottom: 0,
    paddingTop: isCompactHeight ? 6 : 8,
  },

  leaderboardTitle: { 
    fontSize: isCompactHeight ? 18 : 19, 
    fontWeight: '700', 
    color: '#111827',
    letterSpacing: 0.2,
    lineHeight: isCompactHeight ? 22 : 24,
  },

  // Top-3 leaderboard UI
  topThreeContainer: {
    marginTop: 8,
    marginBottom: 10,
    alignItems: 'center',
  },
  topThreeInner: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'center',
    width: '100%',
    paddingHorizontal: 12,
  },
  topThreeItem: {
    alignItems: 'center',
    width: '28%',
  },
  topThreeCenter: {
    width: '44%',
    marginBottom: -14,
  },
  topThreeAvatar: {
    width: 72,
    height: 72,
    borderRadius: 36,
    borderWidth: 3,
    borderColor: '#fff',
    marginBottom: 6,
    backgroundColor: '#eef2f7',
  },
  topThreeAvatarLarge: {
    width: 96,
    height: 96,
    borderRadius: 48,
    borderWidth: 4,
    borderColor: '#fff',
    marginBottom: 4,
    backgroundColor: '#eef2f7',
  },
  topThreePlaceholder: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#94A3B8',
  },
  topThreeInitial: { color: '#fff', fontSize: 28, fontWeight: '900' },
  topThreeName: { fontSize: 13, fontWeight: '700', color: '#111827', textAlign: 'center' },
  topThreeNameCenter: { fontSize: 14 },
  topThreePoints: { fontSize: 12, color: '#6B7280', fontWeight: '600', marginTop: 6 },
  topThreePointsCenter: { color: '#6B7280' },
  topThreeRank: { display: 'none' },
  topThreeRankCenter: { display: 'none' },
  crownWrapper: {
    position: 'absolute',
    top: -8,
    alignSelf: 'center',
    zIndex: 5,
    backgroundColor: 'transparent',
  },
  topBadge: {
    position: 'absolute',
    backgroundColor: '#17263A',
    width: 24,
    height: 24,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
    borderWidth: 2,
    borderColor: '#fff',
    elevation: 4,
  },
  topBadgeText: { color: '#fff', fontWeight: '900', fontSize: 11 },
  tableHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 14,
    marginTop: 8,
    marginBottom: 8,
    borderRadius: 12,
    backgroundColor: '#F8FAFC',
  },
  tableHeaderText: { color: '#6B7280', fontWeight: '700', fontSize: 12 },
  topThreeItemPlaceholder: { width: '30%' },

  // Purple rounded rows for subsequent ranks
  purpleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F8FAFC',
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 14,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#E8EDF3',
  },
  rowLeft: { flexDirection: 'row', alignItems: 'center' },
  rowRankCircle: {
    backgroundColor: '#E5E7EB',
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 16,
    marginRight: 12,
  },
  rowRankText: { color: '#111827', fontWeight: '800' },
  rowAvatar: { width: 42, height: 42, borderRadius: 21, marginRight: 12, borderWidth: 2, borderColor: '#E5E7EB' },
  rowNameText: { color: '#111827', fontWeight: '700', fontSize: 15 },
  rowPointsText: { color: '#374151', fontWeight: '700', fontSize: 14 },

  // PREMIUM BANNER - Eye-catching design
  premiumBanner: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: isCompactHeight ? 14 : 24,
    marginBottom: isCompactHeight ? 10 : 20,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E8EDF3',
  },
  premiumBannerTitle: {
    fontSize: isCompactHeight ? 18 : 20,
    fontWeight: '800',
    color: '#111827',
    marginTop: isCompactHeight ? 8 : 12,
    marginBottom: isCompactHeight ? 6 : 8,
    letterSpacing: 0.3,
  },
  premiumBannerSubtitle: {
    fontSize: isCompactHeight ? 13 : 14,
    color: '#6B7280',
    marginBottom: isCompactHeight ? 10 : 16,
    textAlign: 'center',
    fontWeight: '500',
  },
  premiumBannerButton: {
    backgroundColor: '#17263A',
    paddingHorizontal: isCompactHeight ? 28 : 36,
    paddingVertical: isCompactHeight ? 10 : 14,
    borderRadius: 14,
    elevation: 5,
    shadowColor: '#FFD700',
    shadowOpacity: 0.4,
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 6,
  },
  premiumBannerButtonText: {
    color: '#FFFFFF',
    fontWeight: '800',
    fontSize: isCompactHeight ? 14 : 16,
    letterSpacing: 0.3,
  },

  // LEADERBOARD CARD - Modern card design
  leaderboardCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f5f7fb',
    borderRadius: 18,
    padding: 18,
    marginBottom: 16,
    elevation: 3,
    shadowColor: '#0d1a2f',
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 6,
    borderLeftWidth: 5,
    borderLeftColor: '#667eea',
  },
  firstCardHighlight: { 
    backgroundColor: '#FFF9E6',
    borderLeftColor: '#FFD700',
    elevation: 5,
    borderBottomWidth: 2,
    borderBottomColor: '#FFD700',
    shadowColor: '#FFD700',
    shadowOpacity: 0.15,
  },
  rankIcon: { 
    width: 52, 
    height: 52,
    alignItems: 'center', 
    justifyContent: 'center',
    marginRight: 14,
    backgroundColor: '#e8eff8',
    borderRadius: 26,
    minWidth: 52,
    fontWeight: '800',
    elevation: 3,
    shadowColor: '#667eea',
    shadowOpacity: 0.15,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
  },
  profilePicture: { 
    width: 50, 
    height: 50, 
    borderRadius: 25, 
    marginRight: 14,
    borderWidth: 3,
    borderColor: '#667eea',
    elevation: 3,
    shadowColor: '#667eea',
    shadowOpacity: 0.25,
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 6,
  },
  nameText: { 
    fontSize: 16, 
    color: '#1a2f4d', 
    fontWeight: '800',
    letterSpacing: 0.2,
    flex: 1,
  },
  firstNameHighlight: { 
    color: '#FFD700', 
    fontWeight: '900',
    fontSize: 16,
  },
  pointsBadge: { 
    marginLeft: 'auto',
    backgroundColor: '#667eea',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 14,
    elevation: 4,
    shadowColor: '#667eea',
    shadowOpacity: 0.35,
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 6,
  },
  pointsText: { 
    color: '#FFD700', 
    fontWeight: '900',
    fontSize: 18,
    letterSpacing: 0.3,
  },

  // CARD BUBBLES
  cardBubble1: {
    position: 'absolute',
    width: 80,
    height: 80,
    backgroundColor: 'rgba(102, 126, 234, 0.12)',
    borderRadius: 40,
    top: -20,
    right: -20,
  },
  // cardBubble2: {
  //   position: 'absolute',
  //   width: 50,
  //   height: 50,
  //   backgroundColor: 'rgba(26, 47, 77, 0.08)',
  //   borderRadius: 25,
  //   bottom: -15,
  //   left: -15,
  // },  
  sectionTitle: { fontSize: 20, fontWeight: '800', color: '#fff', marginBottom: 10 },

  blurOverlay: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 28,
    zIndex: 2,
  },

  premiumOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 3,
    paddingHorizontal: 20,
  },

  // Load More Button Styles
  loadMoreButton: {
    backgroundColor: '#17263A',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 18,
    marginTop: 16,
    marginBottom: 16,
    alignSelf: 'center',
  },
  loadMoreButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
  },

  premiumText: { color: '#fff', fontSize: 26, fontWeight: '800', marginBottom: 8, letterSpacing: 0.3 },
  premiumSubText: { color: '#fff', fontSize: 16, marginBottom: 18, fontWeight: '500' },
  premiumButton: {
    backgroundColor: '#1f3a5f',
    paddingHorizontal: 28,
    paddingVertical: 14,
    borderRadius: 20,
    elevation: 4,
  },
  premiumButtonText: { color: '#1f3a5f', fontWeight: '800', fontSize: 16, letterSpacing: 0.2 },
});
