import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F4F6F8',
  },
  headerContainer: {
    width: width - 32,
    alignSelf: 'center',
    minHeight: 150,
    justifyContent: 'center',
    alignItems: 'flex-start',
    borderRadius: 26,
    paddingHorizontal: 20,
    paddingVertical: 22,
    marginTop: 14,
  },
  earningsHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  earningsHeaderTextGroup: {
    flex: 1,
  },
  headerText: {
    color: 'rgba(255,255,255,0.78)',
    fontSize: 13,
    fontWeight: '600',
    marginBottom: 6,
  },
  amountText: {
    color: '#fff',
    fontSize: 32,
    fontWeight: '700',
  },
  weekRangeText: {
    color: '#d7e3f5',
    marginTop: 4,
    fontSize: 12,
  },
  balanceContainer: {
    width: width - 32,
    alignSelf: 'center',
    marginTop: 12,
    backgroundColor: '#fff',
    borderRadius: 22,
    paddingVertical: 18,
    paddingHorizontal: 18,
    borderWidth: 1,
    borderColor: '#E8EDF3',
  },
  balanceTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: '#6B7280',
    marginBottom: 6,
  },
  balanceAmount: {
    fontSize: 24,
    fontWeight: '700',
    color: '#111827',
  },
  balanceSummaryCard: {
    width: width - 32,
    alignSelf: 'center',
    marginTop: 14,
    backgroundColor: '#fff',
    borderRadius: 22,
    padding: 18,
    borderWidth: 1,
    borderColor: '#E8EDF3',
  },
  balanceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  balanceSegment: {
    flex: 1,
    backgroundColor: '#f8fafc',
    borderRadius: 18,
    padding: 14,
  },
  balanceSegmentSpacer: {
    width: 14,
  },
  balanceSegmentTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: '#6B7280',
    marginBottom: 6,
  },
  balanceSegmentAmount: {
    fontSize: 24,
    fontWeight: '700',
    color: '#111827',
  },
  actionIconRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: width - 32,
    alignSelf: 'center',
    marginTop: 16,
  },
  actionIconButton: {
    flex: 0.48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    borderRadius: 16,
  },
  actionIconText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '700',
    marginLeft: 10,
  },
  transactionSection: {
    width: width - 32,
    alignSelf: 'center',
    marginTop: 24,
  },
  transactionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  transactionHeader: {
    fontSize: 16,
    fontWeight: '700',
    color: '#111827',
  },
  transactionCount: {
    fontSize: 12,
    color: '#6B7280',
  },
  transactionItem: {
    width: width - 32,
    alignSelf: 'center',
    backgroundColor: '#fff',
    borderRadius: 18,
    paddingVertical: 16,
    paddingHorizontal: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#E8EDF3',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  transactionLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  transactionIconCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#eff6ff',
    justifyContent: 'center',
    alignItems: 'center',
  },
  transactionDetails: {
    marginLeft: 12,
    flex: 1,
  },
  transactionTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#111827',
  },
  transactionDate: {
    fontSize: 12,
    color: '#6B7280',
    marginTop: 4,
  },
  transactionAmount: {
    fontSize: 15,
    fontWeight: '700',
  },
  transactionEmpty: {
    width: width - 32,
    alignSelf: 'center',
    borderRadius: 18,
    padding: 18,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#E8EDF3',
    alignItems: 'center',
    marginBottom: 12,
  },
  transactionEmptyText: {
    color: '#6B7280',
    fontSize: 14,
  },
  cardsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    marginTop: 16,
  },
  cardContainer: {
    width: (width - 44) / 2,
    backgroundColor: '#fff',
    borderRadius: 20,
    paddingVertical: 20,
    paddingHorizontal: 12,
    marginBottom: 12,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E8EDF3',
  },
  cardAmount: {
    fontSize: 20,
    fontWeight: '700',
    color: '#17263A',
    marginBottom: 8,
  },
  cardTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: '#374151',
  },
  cardDate: {
    fontSize: 11,
    color: '#9CA3AF',
    marginTop: 4,
  },
  contentContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
  },
  text: {
    fontSize: 14,
    color: '#333',
  },
  buttonRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: width - 32,
    alignSelf: 'center',
    marginTop: 14,
  },
  actionButton: {
    flex: 0.48,
    paddingVertical: 14,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '700',
  },
  inputRow: {
    flexDirection: 'row',
    width: width - 32,
    alignSelf: 'center',
    marginTop: 14,
    alignItems: 'center',
  },
  amountInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#D8DEE6',
    borderRadius: 14,
    paddingHorizontal: 15,
    paddingVertical: 12,
    marginRight: 10,
    backgroundColor: '#fff',
    fontSize: 15,
    color: '#111827',
  },
  cashDepositsCard: {
    width: width - 32,
    alignSelf: 'center',
    marginTop: 16,
    backgroundColor: '#fff',
    borderRadius: 22,
    padding: 18,
    borderWidth: 1,
    borderColor: '#E8EDF3',
  },
  cashDepositsTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 12,
  },
  cashDepositItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 12,
    backgroundColor: '#f8fafc',
    borderRadius: 12,
    marginBottom: 8,
  },
  cashDepositInfo: {
    flex: 1,
  },
  cashDepositAmount: {
    fontSize: 18,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 4,
  },
  cashDepositJobId: {
    fontSize: 12,
    color: '#6B7280',
    marginBottom: 2,
  },
  cashDepositDeadline: {
    fontSize: 11,
    color: '#dc2626',
  },
  cashDepositButton: {
    backgroundColor: '#1a2f4d',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  cashDepositButtonText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '600',
  },
});
